http:
  port: ${PORT:8080}

logger: 
  path: ${LOG_PATH:./logs}

  # 'debug', 'info', 'warn', 'error', 'dpanic', 'panic', and 'fatal'
  level: ${LOG_LEVEL:info}

database:
  name: ${DATABASE_NAME:left-it}
  host: ${DATABASE_HOST:localhost}
  port: ${DATABASE_PORT:5432}
  username: ${DATABASE_USERNAME:left-it}
  password: ${DATABASE_PASSWORD}

  # 'disable' and 'enable'
  ssl: ${DATABASE_SSL:disable}
